/* 
 * Simple Inventory API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Localdb
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocaldbTests
    {
        // TODO uncomment below to declare an instance variable for Localdb
        //private Localdb instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Localdb
            //instance = new Localdb();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Localdb
        /// </summary>
        [Test]
        public void LocaldbInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Localdb
            //Assert.IsInstanceOfType<Localdb> (instance, "variable 'instance' is a Localdb");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
